//! Voltip's phone app as a React Native shell (docs/mobile-rn.md). The command surface of the Tauri
//! phone shell (`apps/mobile/src-tauri`) behind one entry, [`Shell::invoke`]: a command name and its
//! arguments in, JSON or an error text out, and every `UiEvent` handed to the [`Host`]. The app
//! reaches it through the UniFFI interface in [`ffi`] (Kotlin bindings on Android, generated by
//! scripts/build-android-rn.sh); everything here is platform-free but the secret store, and tested
//! on the build host with [`host::RecordingHost`].

#![warn(missing_docs)]

uniffi::setup_scaffolding!();

pub mod clipboard;
pub mod commands;
pub mod ffi;
pub mod host;
pub mod legacy;
pub mod meter;
pub mod microphone;
pub mod shell;
pub mod update;

pub use ffi::{HostError, PlatformHost, ShellError, VoltipShell};
pub use host::Host;
pub use shell::Shell;
